### ISSUE TITLE
Documentation about PDF generation

### ISSUE THREAD

**Issue by pmithrandir** [liuggio/ExcelBundle#38]
Hello,

I'm using the extension with Excel generation, and we want now to generate PDF file also.

We di the same kind of script, but as soon as we put : 

```
                $excelService = $this->get('xls.service_pdf');
```

in the code, we get this error : 
 PDF Rendering library has not been defined.
500 Internal Server Error - Exception 

i'm totally ok to define this library, but where should I do that ?

Is there any documentation about that ?
I think we have to add something in config.php, but what and under which title, that's a good question.

I think an example of configuration would be great.

Thank you,
Pierre

PS : I went on PHP Excel website, but I got no explanation I was able to understand enough to apply them on the Symfony Bundle.

**Comment by maestrojosiah** [comment]
@liuggio , I love your works. However, everywhere I find a question addressed to you, you are either too busy or rude. I know that you have already done a lot by putting stuff on open-source, but a step further would make programmers happy of you; especially new programmers. Your awesome project liuggio/excelbundle lacks explanation of how to make pdf docs, while every other place it is indicated that there is a way to do that. Since 2013, you have been to busy to help us, and I wish I was a guru like you. I would make programmers proud.

**Comment by xeux** [comment]
Since this is a Bundle for the PHPExcel library I recommend to read the PHPExcel documentation at: https://github.com/PHPOffice/PHPExcel/issues/152
